In [1]:
import pandas as pd

In [25]:
data = pd.read_csv(
    "data_after_preprocessing.csv",
    names=[
        "kilometrage",
        "carrosserie",
        "energie",
        "puissance",
        "boite",
        "transmission",
        "couleur",
        "model",
        "age",
        "brand",
        "price",
    ],
    encoding="utf-8",
    error_bad_lines=False,
)

In [26]:
a = "a b cc "

In [34]:
a.rsplit(" ",1)[0]

'a b cc'

' '

In [35]:
def del_space(model):
    model = model.rsplit(" ",1)[0]
    return model

In [36]:
data["model"]=data["model"].apply(del_space)

In [37]:
model = data["model"].unique().tolist()

In [38]:
model

['GOLF 7',
 'XE',
 'CLASSE E',
 'CAYENNE',
 'CLASSE S',
 'ZS',
 '3',
 'SÉRIE 3',
 'COOPER',
 'CLASSE C',
 'Q7',
 'Q5',
 'S80',
 'GOLF 6',
 'A4',
 'RIO',
 'PRADO',
 'CLASSE A',
 'LAND CRUISER',
 'CHEROKEE',
 'GLA',
 'FIESTA',
 'GS',
 'POLO',
 'PANDA',
 'RANGE ROVER ',
 '500',
 'RANGE ROVER  ',
 'MACAN',
 'HS',
 'X6',
 'ATECA',
 'GLC',
 'CLS',
 'Q3',
 'H-1',
 'PASSAT CC',
 'RANGER',
 'SÉRIE 5',
 '6',
 'IRIS',
 '2008',
 'PASSAT',
 'C4',
 'TOUAREG',
 'GOLF 5',
 'LEON',
 'DOBLO',
 'CERATO',
 'YARIS',
 'TOURAN',
 'AGE',
 'FOCUS',
 'KADJAR',
 'SÉRIE 1',
 'I20',
 'ML',
 'H6',
 '301',
 'DS3',
 'SWIFT',
 'HILUX',
 'ACTYON S',
 'DS5',
 'PAJERO',
 'ARONA',
 'OPTIMA',
 'H2',
 'A5',
 'CADDY',
 '407',
 'COOPER S',
 'K2700',
 'C5',
 '206',
 'ESCALADE',
 'AVEO',
 'AMAROK',
 '208',
 'DS4',
 'PICANTO',
 'KUV 100',
 'H9',
 'BERLINGO ',
 'C-HR',
 'CRUZE',
 'E3',
 'YX KENBO S3',
 'QQ',
 'TIVOLI',
 'COOPER COUNTRY MAN',
 'SÉRIE 4',
 'A3',
 'DUSTER',
 'JETTA',
 'A8',
 '500X',
 'YPSILON',
 'XF',
 'PANDA CITY CROSS',
 '',
 'TWINGO',
 'X5',
 '107',
 'CLIO CAMPUS',
 'MEGANE',
 'BT-50',
 'QASHQAI',
 'XENON',
 'FIORINO',
 'SPRINTER',
 'SORENTO',
 'DAILY',
 'BIPPER',
 'NEMO',
 'JUKE',
 'ALTEA',
 'FUSION',
 'XLV',
 'CLASSE GL',
 'SONIC',
 'TIPO ',
 '3008',
 'A6',
 'S50',
 'RIFTER',
 'DISCOVERY ',
 'C3',
 'WALL H5',
 'EXPERT',
 'PICKUP',
 'GRANDE PUNTO',
 'D-MAX',
 'TT',
 '300C',
 'CLA',
 'LAGUNA',
 'OCTAVIA',
 'GRAND I10',
 'CX-7',
 'TIGGO 2',
 'X1',
 'DEFENDER ',
 'G35',
 'PATROL',
 'NEW BEETLE',
 '5',
 'CLIO CLASSIC',
 'ASTRA',
 'MODUS',
 'ROMEO GIULIETTA',
 '308',
 'ACCENT',
 'ELANTRA',
 'C-ELYSÉE',
 'TIGUAN',
 'SILVERADO',
 'IBIZA',
 'HR-V',
 'PANAMERA',
 'X3',
 'RAV 4',
 'WALL M4',
 'CAPTIVA',
 'PALIO',
 'Q2',
 'FLUENCE',
 'TRANER FOURGON 6.1',
 '2',
 'ECO',
 'CLIO',
 'SYMBOL',
 'ARRIZO 5',
 'MIRAGE',
 'SPARK',
 'KA',
 'FORFOUR',
 'MICRA',
 'FREELANDER ',
 'V70',
 'PUNTO',
 'SOUL',
 'R 19',
 'SANTA FE',
 '4008',
 '207',
 '508',
 'CX-5',
 'KORANDO',
 '220',
 '206+',
 'ARMADA',
 'CX-9',
 'IX35',
 'VELOSTER',
 'I10',
 'ADAM',
 'COMPASS',
 'X2',
 'VITARA',
 'CAPTUR',
 'BALENO',
 '250',
 'A1',
 'SÉRIE 7',
 '200',
 'XJ',
 'X4',
 'SÉRIE 2',
 'GLE',
 'PARTNER',
 'RENEGADE',
 'CC',
 'ROMEO MITO',
 'FIGO',
 'C1',
 'EXPLORER',
 'AX',
 'AUTRE',
 '406',
 '1007',
 'DUCATO',
 'EXEO',
 '106',
 'SANDERO',
 'CORSA',
 'SUNNY',
 'UP',
 'SIENA',
 'SPACE STAR',
 'AVANZA',
 'DOKKER',
 'CLASSE V',
 'LT',
 'GOLF 4',
 'QUBO',
 'L200 DOUBLE CABINE',
 '307',
 'PUNTO CLASSIC',
 'S60',
 'KUGA',
 'YX KENBO S2',
 'K01',
 'MONDEO',
 'JUMPY COMBI',
 'CLK',
 'PUNTO EVO',
 'FABIA',
 'PARTNER TEPEE',
 '4',
 'CIAZ',
 'GOLF 3',
 'KANGOO',
 'PUNTO POP',
 'CLASSE B',
 'JUMPER',
 'TIGGO 3',
 'LOGAN MCV',
 'X-TYPE',
 'NAVARA',
 'ROVER ',
 'V40 CROSS COUNTRY',
 'IMPREZA',
 'MURANO',
 'PARTNER ORIGIN',
 'LOGAN',
 '5008',
 'M1',
 'LATITUDE',
 'AVENGER',
 'X-TRAIL',
 'COROLLA',
 'R 9',
 'MASTER',
 'CRETA',
 'WALL C30']

In [39]:
brand = data["brand"].unique().tolist()

In [40]:
brand

['VOLKSWAGEN',
 'JAGUAR',
 'MERCEDES-BENZ',
 'PORSCHE',
 'MG',
 'MAZDA',
 'BMW',
 'MINI',
 'AUDI',
 'VOLVO',
 'KIA',
 'TOYOTA',
 'JEEP',
 'FORD',
 'FIAT',
 'LANDROVER',
 'SEAT',
 'HYUNDAI',
 'WALLYSCAR',
 'PEUGEOT',
 'CITROËN',
 'RENAULT',
 'HAVAL',
 'SUZUKI',
 'SSANGYONG',
 'MITSUBISHI',
 'HUMMER',
 'CADILLAC',
 'CHEVROLET',
 'MAHINDRA',
 'CHERY',
 'BAIC',
 'DACIA',
 'LANCIA',
 'MAHINDRAORPIO',
 'NISSAN',
 'TATA',
 'IVECO',
 'DONGFENG',
 'GREAT',
 'ISUZU',
 'CHRYSLER',
 'SKODA',
 'INFINITI',
 'OPEL',
 'ALFA',
 'HONDA',
 'SMART',
 'DS',
 'DFSK',
 'SUBARU',
 'DODGE']

In [41]:
brand.sort()

In [42]:
data_=[]

for b in brand:
    x_=[]
    for i in data.index:
        if b == data["brand"][i]:
            if data["model"][i] not in x_:
                x_.append(data["model"][i])
    data_.append(x_)

In [43]:

data_

[['ROMEO GIULIETTA', 'ROMEO MITO'],
 ['Q7', 'Q5', 'A4', 'Q3', 'A5', 'A3', 'A8', 'A6', 'TT', 'Q2', 'A1'],
 ['YX KENBO S3', 'YX KENBO S2'],
 ['SÉRIE 3',
  'X6',
  'SÉRIE 5',
  'SÉRIE 1',
  'SÉRIE 4',
  'X5',
  'X1',
  'X3',
  'X2',
  'SÉRIE 7',
  'X4',
  'SÉRIE 2',
  'M1'],
 ['ESCALADE'],
 ['E3', 'QQ', 'TIGGO 2', 'ARRIZO 5', 'TIGGO 3'],
 ['AVEO', 'CRUZE', 'SONIC', 'SILVERADO', 'CAPTIVA', 'SPARK'],
 ['300C'],
 ['C4',
  'DS3',
  'DS5',
  'C5',
  'DS4',
  'BERLINGO ',
  'NEMO',
  'C3',
  'C-ELYSÉE',
  'C1',
  'AX',
  'JUMPY COMBI',
  'JUMPER'],
 ['DUSTER', 'SANDERO', 'DOKKER', 'LOGAN MCV', 'LOGAN'],
 ['K01'],
 ['AVENGER'],
 ['S50'],
 ['3', '4'],
 ['PANDA',
  '500',
  'DOBLO',
  '500X',
  'PANDA CITY CROSS',
  'FIORINO',
  'TIPO ',
  'GRANDE PUNTO',
  'PALIO',
  'PUNTO',
  'DUCATO',
  'SIENA',
  'QUBO',
  'PUNTO CLASSIC',
  'PUNTO EVO',
  'PUNTO POP'],
 ['FIESTA',
  'RANGER',
  'FOCUS',
  'FUSION',
  'ECO',
  'KA',
  'FIGO',
  'EXPLORER',
  'AUTRE',
  'KUGA',
  'MONDEO'],
 ['WALL H5', 'WALL M4', 'WALL C30'],
 ['H6', 'H9', 'H2'],
 ['HR-V'],
 ['H2'],
 ['H-1',
  'I20',
  'GRAND I10',
  'ACCENT',
  'ELANTRA',
  'SANTA FE',
  'IX35',
  'VELOSTER',
  'I10',
  'CRETA'],
 ['G35'],
 ['D-MAX'],
 ['DAILY'],
 ['XE', 'XF', 'XJ', 'X-TYPE'],
 ['CHEROKEE', 'COMPASS', 'RENEGADE'],
 ['RIO', 'CERATO', 'AGE', 'OPTIMA', 'K2700', 'PICANTO', 'SORENTO', 'SOUL'],
 ['YPSILON'],
 ['RANGE ROVER ',
  'RANGE ROVER  ',
  'DISCOVERY ',
  'DEFENDER ',
  'FREELANDER ',
  'ROVER '],
 ['KUV 100', ''],
 [''],
 ['3', 'BT-50', '6', 'CX-7', '2', 'CX-5', 'CX-9'],
 ['CLASSE E',
  'CLASSE S',
  'CLASSE C',
  'CLASSE A',
  'GLA',
  'GLC',
  'CLS',
  'ML',
  'SPRINTER',
  'CLASSE GL',
  'CLA',
  '220',
  '250',
  '200',
  'GLE',
  'CLASSE V',
  'CLK',
  'CLASSE B'],
 ['ZS', 'GS', 'HS', '6', '', '5', '3'],
 ['COOPER', 'COOPER S', 'COOPER COUNTRY MAN'],
 ['PAJERO', 'MIRAGE', 'SPACE STAR', 'L200 DOUBLE CABINE'],
 ['QASHQAI',
  'JUKE',
  'PATROL',
  'MICRA',
  'ARMADA',
  'SUNNY',
  'NAVARA',
  'MURANO',
  'X-TRAIL'],
 ['ASTRA', 'ADAM', 'CORSA'],
 ['2008',
  '301',
  '407',
  '206',
  '208',
  '107',
  'BIPPER',
  '3008',
  'RIFTER',
  'EXPERT',
  'PICKUP',
  '308',
  '4008',
  '207',
  '508',
  '206+',
  'PARTNER',
  '406',
  '1007',
  '106',
  '307',
  'PARTNER TEPEE',
  'PARTNER ORIGIN',
  '5008'],
 ['CAYENNE', 'MACAN', 'PANAMERA'],
 ['KADJAR',
  'TWINGO',
  'CLIO CAMPUS',
  'MEGANE',
  'LAGUNA',
  'CLIO CLASSIC',
  'MODUS',
  'FLUENCE',
  'CLIO',
  'SYMBOL',
  'R 19',
  'CAPTUR',
  'KANGOO',
  'LATITUDE',
  'R 9',
  'MASTER'],
 ['ATECA', 'LEON', 'ARONA', 'ALTEA', 'IBIZA', 'EXEO'],
 ['OCTAVIA', 'FABIA'],
 ['FORFOUR'],
 ['ACTYON S', 'TIVOLI', 'XLV', 'KORANDO'],
 ['IMPREZA'],
 ['SWIFT', 'VITARA', 'BALENO', 'CIAZ'],
 ['XENON'],
 ['PRADO',
  'LAND CRUISER',
  'YARIS',
  'HILUX',
  'C-HR',
  'RAV 4',
  'AVANZA',
  'COROLLA'],
 ['GOLF 7',
  'GOLF 6',
  'POLO',
  'PASSAT CC',
  'PASSAT',
  'TOUAREG',
  'GOLF 5',
  'TOURAN',
  'CADDY',
  'AMAROK',
  'JETTA',
  'NEW BEETLE',
  'TIGUAN',
  'TRANER FOURGON 6.1',
  'CC',
  'UP',
  'LT',
  'GOLF 4',
  'GOLF 3'],
 ['S80', 'V70', 'S60', 'V40 CROSS COUNTRY'],
 ['IRIS']]

In [44]:
brand_model=pd.DataFrame(brand)

In [45]:
brand_model

                0
0            ALFA
1            AUDI
2            BAIC
3             BMW
4        CADILLAC
5           CHERY
6       CHEVROLET
7        CHRYSLER
8         CITROËN
9           DACIA
10           DFSK
11          DODGE
12       DONGFENG
13             DS
14           FIAT
15           FORD
16          GREAT
17          HAVAL
18          HONDA
19         HUMMER
20        HYUNDAI
21       INFINITI
22          ISUZU
23          IVECO
24         JAGUAR
25           JEEP
26            KIA
27         LANCIA
28      LANDROVER
29       MAHINDRA
30  MAHINDRAORPIO
31          MAZDA
32  MERCEDES-BENZ
33             MG
34           MINI
35     MITSUBISHI
36         NISSAN
37           OPEL
38        PEUGEOT
39        PORSCHE
40        RENAULT
41           SEAT
42          SKODA
43          SMART
44      SSANGYONG
45         SUBARU
46         SUZUKI
47           TATA
48         TOYOTA
49     VOLKSWAGEN
50          VOLVO
51      WALLYSCAR

In [46]:
brand_model["model"]=data_

In [47]:
brand_model

                0                                              model
0            ALFA                      [ROMEO GIULIETTA, ROMEO MITO]
1            AUDI       [Q7, Q5, A4, Q3, A5, A3, A8, A6, TT, Q2, A1]
2            BAIC                         [YX KENBO S3, YX KENBO S2]
3             BMW  [SÉRIE 3, X6, SÉRIE 5, SÉRIE 1, SÉRIE 4, X5, X...
4        CADILLAC                                         [ESCALADE]
5           CHERY               [E3, QQ, TIGGO 2, ARRIZO 5, TIGGO 3]
6       CHEVROLET    [AVEO, CRUZE, SONIC, SILVERADO, CAPTIVA, SPARK]
7        CHRYSLER                                             [300C]
8         CITROËN  [C4, DS3, DS5, C5, DS4, BERLINGO , NEMO, C3, C...
9           DACIA        [DUSTER, SANDERO, DOKKER, LOGAN MCV, LOGAN]
10           DFSK                                              [K01]
11          DODGE                                          [AVENGER]
12       DONGFENG                                              [S50]
13             DS                                             [3, 4]
14           FIAT  [PANDA, 500, DOBLO, 500X, PANDA CITY CROSS, FI...
15           FORD  [FIESTA, RANGER, FOCUS, FUSION, ECO, KA, FIGO,...
16          GREAT                       [WALL H5, WALL M4, WALL C30]
17          HAVAL                                       [H6, H9, H2]
18          HONDA                                             [HR-V]
19         HUMMER                                               [H2]
20        HYUNDAI  [H-1, I20, GRAND I10, ACCENT, ELANTRA, SANTA F...
21       INFINITI                                              [G35]
22          ISUZU                                            [D-MAX]
23          IVECO                                            [DAILY]
24         JAGUAR                               [XE, XF, XJ, X-TYPE]
25           JEEP                      [CHEROKEE, COMPASS, RENEGADE]
26            KIA  [RIO, CERATO, AGE, OPTIMA, K2700, PICANTO, SOR...
27         LANCIA                                          [YPSILON]
28      LANDROVER  [RANGE ROVER , RANGE ROVER  , DISCOVERY , DEFE...
29       MAHINDRA                                        [KUV 100, ]
30  MAHINDRAORPIO                                                 []
31          MAZDA                 [3, BT-50, 6, CX-7, 2, CX-5, CX-9]
32  MERCEDES-BENZ  [CLASSE E, CLASSE S, CLASSE C, CLASSE A, GLA, ...
33             MG                            [ZS, GS, HS, 6, , 5, 3]
34           MINI             [COOPER, COOPER S, COOPER COUNTRY MAN]
35     MITSUBISHI   [PAJERO, MIRAGE, SPACE STAR, L200 DOUBLE CABINE]
36         NISSAN  [QASHQAI, JUKE, PATROL, MICRA, ARMADA, SUNNY, ...
37           OPEL                               [ASTRA, ADAM, CORSA]
38        PEUGEOT  [2008, 301, 407, 206, 208, 107, BIPPER, 3008, ...
39        PORSCHE                         [CAYENNE, MACAN, PANAMERA]
40        RENAULT  [KADJAR, TWINGO, CLIO CAMPUS, MEGANE, LAGUNA, ...
41           SEAT           [ATECA, LEON, ARONA, ALTEA, IBIZA, EXEO]
42          SKODA                                   [OCTAVIA, FABIA]
43          SMART                                          [FORFOUR]
44      SSANGYONG                   [ACTYON S, TIVOLI, XLV, KORANDO]
45         SUBARU                                          [IMPREZA]
46         SUZUKI                      [SWIFT, VITARA, BALENO, CIAZ]
47           TATA                                            [XENON]
48         TOYOTA  [PRADO, LAND CRUISER, YARIS, HILUX, C-HR, RAV ...
49     VOLKSWAGEN  [GOLF 7, GOLF 6, POLO, PASSAT CC, PASSAT, TOUA...
50          VOLVO                 [S80, V70, S60, V40 CROSS COUNTRY]
51      WALLYSCAR                                             [IRIS]

In [49]:
brand_model.to_csv("brand_model.txt",encoding="utf-8",index=False,header=None)